In [4]:
import numpy as np

# create a random matrix 
A = np.random.rand(5, 3)

# Perform SVD

U, S, VT = np.linalg.svd(A)

#Choose number of singular valuesto keep

k = 2

# Reduce the dimensions

U_k = U[:,:k]
S_k = np.diag(S[:k])
VT_k = VT[:k, :]

#Reconstruct the reduced matrix

A_reduced = np.dot(U_k, np.dot(S_k, VT_k))
A

array([[0.63789305, 0.54065575, 0.25222185],
       [0.00677994, 0.34136061, 0.53601795],
       [0.00232474, 0.43482396, 0.04061069],
       [0.58103605, 0.64147475, 0.96416404],
       [0.30016817, 0.71313382, 0.72839895]])

In [5]:
from skimage.color import rgb2gray
from skimage import data
import matplotlib.pyplot as plt
import numpy as np
from scipy.linalg import svd

C:\ProgramData\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


In [8]:
# Define matrix

X = np.array([[3, 3, 2], [2, 3, -2]])
print(X)

# perform svd

U, S, VT = svd(X)

# Print Different Components

print("U\n", U)
print("Singular array\n", S)
print("VT\n", VT)


[[ 3  3  2]
 [ 2  3 -2]]
U
 [[ 0.7815437 -0.6238505]
 [ 0.6238505  0.7815437]]
Singular array
 [5.54801894 2.86696457]
VT
 [[ 0.64749817  0.7599438   0.05684667]
 [-0.10759258  0.16501062 -0.9804057 ]
 [-0.75443354  0.62869461  0.18860838]]


In [12]:
import numpy as np

# Step 2 Create a matrix

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

# Step 3 Perform SVD

U, S, VT = np.linalg.svd(A, full_matrices = False)

print("Matrix A\n", A)
print("Matrix U\n", U)
print("Matrix S\n", S)
print("Matrix VT\n", VT)

# Construct the diagonal matrix for for singular values

Sigma = np.diag(S)

# Reconstruct the original matrix

A_ressurected = np.dot(U, np.dot(Sigma, VT))

print("Reconstructed matrix A\n", A_ressurected)


Matrix A
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Matrix U
 [[-0.14087668  0.82471435  0.53358462]
 [-0.34394629  0.42626394 -0.8036038 ]
 [-0.54701591  0.02781353  0.00645373]
 [-0.75008553 -0.37063688  0.26356544]]
Matrix S
 [2.54624074e+01 1.29066168e+00 1.38648772e-15]
Matrix VT
 [[-0.50453315 -0.5745157  -0.64449826]
 [-0.76077568 -0.05714052  0.64649464]
 [-0.40824829  0.81649658 -0.40824829]]
Reconstructed matrix A
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
