In [1]:
import numpy as np

### Creating Numpy array 

In [4]:
arr = np.random.rand(10)
arr

array([0.95827094, 0.48676515, 0.37193983, 0.8478209 , 0.45252868,
       0.09007712, 0.83920199, 0.92623283, 0.39575424, 0.32346455])

### 4 Arithmetic Operations

In [6]:
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
arr1, arr2

(array([0.90905539, 0.80272166, 0.15990637, 0.80295638, 0.46627652,
        0.8602018 , 0.87771089, 0.50681716, 0.50335213, 0.73954083]),
 array([0.06974244, 0.53032963, 0.19866685, 0.90986002, 0.0907904 ,
        0.93492645, 0.3114941 , 0.72970775, 0.0316456 , 0.19571057]))

In [9]:
add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
div = arr1/arr2 

add, sub, mul, div

(array([0.97879783, 1.33305129, 0.35857321, 1.7128164 , 0.55706692,
        1.79512825, 1.18920499, 1.23652491, 0.53499773, 0.9352514 ]),
 array([ 0.83931295,  0.27239203, -0.03876048, -0.10690364,  0.37548611,
        -0.07472465,  0.56621678, -0.22289059,  0.47170652,  0.54383025]),
 array([0.06339974, 0.42570708, 0.03176809, 0.73057791, 0.04233343,
        0.80422542, 0.27340177, 0.36982841, 0.01592888, 0.14473596]),
 array([13.034465  ,  1.51362779,  0.8048971 ,  0.8825054 ,  5.13574682,
         0.9200743 ,  2.81774479,  0.69454814, 15.90590965,  3.77874741]))

### Indexing

In [26]:
arr2d = np.array(([1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]))
arr1d = np.array((1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12))

In [27]:
print(arr1d[4])
print(arr2d[1][3])

5
8


### Slicing

In [31]:
print(arr1d[1:5]) # slicing from index 1 to index 4
print(arr1d[1:10:2]) # print elements from index 1 to 10 with step 2
print(arr1d[::2]) # prints every other element in the array
print(arr1d[-4:-1]) # negative indexing

[2 3 4 5]
[ 2  4  6  8 10]
[ 1  3  5  7  9 11]
[ 9 10 11]


### Broadcasting Array

In [32]:
b = 4.0
arr = arr1d * b
print(arr)

[ 4.  8. 12. 16. 20. 24. 28. 32. 36. 40. 44. 48.]
